@extends('layouts.guest')

@section('page_name') Terms and Conditions @endsection
@section('content')
<div class="container">
      <div class="col-md-12">
          <div class="panel-heading"><center><strong>Terms and Conditions</strong></center></div>
          <div class="glass-panal-default">
              <div class="panel-body">
                  <p align="justify"><u><strong>Terms and Conditions</strong></u></p>
                  <p align="justify">This record of document is in electric form pertaining to the Information Technology Act 2000 and rules there under and as and when amended. The electronic document is generated by a computer system and does not require any physical or digital signature.</p>
                  <p align="justify">This record of document is in accordance with provisions of Rule 3(1) of the Information Technology Rules 2011, that requires publishing the rules and regulations , Privacy policy and the Terms and Conditions for accessing or using <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a>.</p>
                  <p align="justify">Usage of this website <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a>, a matrimony services is subject to your acceptance with best of your knowledge. As you browse, search or create profile , it implies that you are accepting and agreeing to the Terms and Conditions of the website <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a>. Hence, you are requested to carefully go through the Terms and Conditions before continuing with the website. You must forfeit this website, if you no longer want to agree to the Terms and Conditions of this website <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a>.</p>
                  <p align="justify">You are the user either registered member or unregistered member of PonnuMaapillai. <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a> (PonnuMaapillai) is the service provider, web designer and content writer of this website.</p>
                  <p align="justify"><a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a> is registered under <strong>GSTIN 33ALOPR7902H1ZT</strong></p>
                  <p align="justify"><a name="_GoBack"></a> Regd Address &ndash; A 132 Swami Sachithanandha Street,</p>
                  <p align="justify">A &ndash;Colony, Jothinagar, Pollachi -642001</p>
                  <p align="justify">Coimbatore (dt)</p>
                  <p align="justify">Tamilnadu.</p>
                  <p align="justify"><u><strong>Outlook and Aim of Website.</strong></u></p>
                  <p align="justify"><a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a> will act as a server to be utilised by registered users to find their eligible , suitable and lawful partners. PonnuMaapillai will also assist members to utilise the service of registration centres situated throughout Tamilnadu.</p>
                  <p align="justify">The profiles in data base are classified according to their caste , subsect , kulam and language. PonnuMaapillai is a paid service charging a nominal price for their service, a customer can afford to.</p>
                  <p align="justify">The results of the search considers their stars in matching the profiles as default. It is a preliminary investigation and it is mandatory for every customer to proceed further by detailed investigation of the profile.</p>
                  
                  <p align="justify"><u><strong>Requirements</strong></u></p>
                  <p align="justify">PonnuMaapillai service is exclusively permitted for</p>
                  <p align="justify">Indian Nationals.</p>
                  <p align="justify">Non Resident Indians.</p>
                  <p align="justify">Persons of Indian Origin.</p>
                  <p align="justify">18 years of age and above for females and 21 years and above for males.</p>
                  <p align="justify">Legally competent to marry as per laws pertaining to Indian Penal Code.</p>
                  <p align="justify"><u><strong>Registration</strong></u></p>
                  <p align="justify">Either you can register through a valid mobile number on your own or with the assistance of our registered centres spread throughout Tamilnadu in PonnuMaapillai.</p>
                  <p align="justify">On registering you are advised to furnish true, accurate, acceptable information including the photos you share.</p>
                  <p align="justify">PonnuMaapillai will share your profile details to other PonnuMaapillai customers and members are solely responsible for the personal, family and birth details shared in the website.</p>
                  <p align="justify">If it is found the details shared by PonnuMaapillai member is unfair, untrue and not acceptable, the membership will be immediately terminated without any notice and the member has to forfeit the registration fee paid.</p>
                  <p align="justify">Business or individuals carrying on similar or competitive business cannot register on PonnuMaapillai. If found any misuse of PonnuMaapillai website by unauthorised persons or by members, appropriate legal action will be taken.</p>
                  <p align="justify"><u><strong>Role of PonnuMaapillai and it&rsquo;s members.</strong></u></p>
                  <p align="justify">PonnuMaapillai ensures to serve it&rsquo;s registered members honestly , effectively and efficiently .</p>
                  <p align="justify">Through automated search you will be provided with matching profiles for your star. Members profile will be shared to eligible profiles according to their preferences.</p>
                  <p align="justify">On registering after successful payment sms will be sent to matching profiles based on their star matching. PonnuMaapillai cannot guarantee or assume responsibility for any specific results from the use of the details given in the users profile of <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a>.</p>
                  <p align="justify">Members are requested to keep their login details safe and confidential.</p>
                  <p align="justify">Members are requested to be cautious while shortlisting any profiles. PonnuMaapillai shall not be liable for short coming due to any misinterpretations made by any of its members.</p>
                  <p align="justify">Members are expected to thoroughly investigate each and every parameter of the datas given in the profile before coming to any conclusion.</p>
                  <p align="justify">PonnuMaapillai site provides the matching profiles relating to your star. It is very preliminary and is exercised to make easy the process of selection.</p>
                  <p align="justify">Still it is very preliminary and members are strictly requested to investigate thoroughly by all means before coming to any conclusion.</p>
                  <p align="justify">Members cannot transfer or transform their membership, such an act shall be treated as violation of terms and conditions.</p>
                  <!-- <p align="justify"><br /> </p> -->
                  <p align="justify"><u><strong>Customer Care / Customer Service</strong></u></p>
                  <p align="justify"><a href="mailto:info@ponnumaapillai.com">info@ponnumaapillai.com</a></p>
                  <p align="justify">Contact number -+919600577751</p>
                  <p align="justify">A 132 Swami Sachithanandha street,</p>
                  <p align="justify">A Colony , Jothi Nagar,</p>
                  <p align="justify">Pollachi &ndash; 642001</p>
                  <p align="justify">Coimbatore (dt), Tamilnadu ,India</p>
                  <p align="justify"><u><strong>Confidentiality</strong></u></p>
                  <p align="justify">PonnuMaapillai will maintain confidentiality of all personal information other than those meant for sharing with the eligible members. However , PonnuMaapillai may divulge such information if required by law.</p>
                  <p align="justify"><u><strong>Disclosure of datas provided in the profile.</strong></u></p>
                  <p align="justify">PonnuMaapillai will take necessary steps to safeguard the confidentiality of personal information given by the members , but any information transacted through internet work cannot be made absolutely secure. Members on accepting the Terms and Conditions accept to the thing that copying the datas by using the technology or any other means of cyber theft cannot be secured by PonnuMaapillai website. PonnuMaapillai website is not responsible for disclosure of any data due to errors for disclosure of any data due to errors in transmissions or unauthorised acts of third persons. It is requested to change the password often to secure interference of third parties.</p>
                  <p align="justify"><u><strong>Dispute between members.</strong></u></p>
                  <p align="justify">PonnuMaapillai is not an intermediator or agent for any PonnuMaapillai member. PonnuMaapillai will not interfere in any exchange of communication between registered members and outcome of their discussions.</p>
                  <p align="justify">Members of PonnuMaapillai are solely responsible for any communication (Verbal. mail or written) between any other member of PonnuMaapillai. PonnuMaapillai shall not be legally involved in disputes, litigation arising between any PonnuMaapillai member.</p>
                  <p align="justify"><u><strong>Content Right</strong></u></p>
                  <p align="justify"><a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a> domain is an exclusive matrimony website.</p>
                  <p align="justify">The members who provide their personal information on their profile in the website or modify it later are solely responsible for the content. By creating your profile in the website , you authorise PonnuMaapillai to use , reproduce , distribute publish, communicate to public , law enforcement agencies, court of Law.</p>
                  <p align="justify">PonnuMaapillai does not investigate or monitor the content given by the member . If the input datas found irrelevant or inappropriate, PonnuMaapillai has rights to delete the content or suspend the membership of the registered member.</p>
                  <p align="justify"><u><strong>Third Party Website</strong></u></p>
                  <p align="justify">By agreeing to the terms and conditions, a registered PonnuMaapillai member agrees to allow third parties to put up advertisement on <a href="http://www.pommumaapillai.com/">www.pommumaapillai.com</a>. Third party websites to which links are provided on websites are not governed by our Terms and Conditions . All such third party websites are governed by their own Terms and Conditions for use and privacy policy and in case of conflict the Terms and Conditions of the third party website shall prevail.</p>
                  <p align="justify"><u><strong>Limitation of Liability</strong></u></p>
                  <p align="justify">PonnuMaapillai website wishes to inform that exchange of profile through PonnuMaapillai website should not be in any case taken into consideration as a matrimonial offer, recommendation, tips or assurance given to the PonnuMaapillai registered member by the website.</p>
                  <p align="justify">PonnuMaapillai website shall under no circumstances be liable or responsible to the member or authorised party for any direct, indirect , special exemplary , incidental or consequential damages of any character including without limitation damages resulting from the use of our website.</p>
                  <p align="justify"><u><strong>General</strong></u></p>
                  <p align="justify">PonnuMaapillai reserves the right to delete , if it is worth in order to follow the Terms and Conditions of the website, those relating to providing any vulgar, obscene, blasphemous, defamatory of any person. Apart from these the following things will be deleted and appropriate legal action will be taken</p>
                  <p align="justify">Posting harmful, Vulgar, pornographic, objectionable with respect to race, religion, nationality, gender, or otherwise illegal and unlawful activity.</p>
                  <p align="justify">Postings violating any law.</p>
                  <p align="justify">Wrongful information misleading other members.</p>
                  <p align="justify">Infringement of any trademark, copyright and other proprietary right.</p>
                  <p align="justify"><u><strong>Jurisdiction </strong></u></p>
                  <p align="justify">All PonnuMaapillai registered members are under the Territorial jurisdiction of Chennai.</p>
                  <p align="justify">All the registered members of PonnuMaapillai agree to the condition that all disputes and differences if any shall be governed by the Laws under Indian Penal code under the Jurisdiction of appropriate court of law in Chennai, Tamilnadu.</p>
                  <p align="justify"><u><strong>Charges and mode of payment</strong></u>.</p>
                  <p align="justify">PonnuMaapillai charges Rupees 600 per registration for one year as an introductory offer. Mode of payment is online through our stipulated payment gateway.</p>
                  <p align="justify">PonnuMaapillai uses third party payment gateways for collection of credit/debit card/Net Banking or other online payment options. In case of payment gateway failure the same would be communicated to the PonnuMaapillai member by the payment gateway provider. PonnuMaapillai shall not be responsible for Extra currency/conversion charges / deductions /error issues from payment gateway . In case of failed transactions, which result in no services, PonnuMaapillai offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customer card/bank accounts through the payment gateway.</p>
                  <p align="justify"><u><strong>Renewal</strong></u></p>
                  <p align="justify">All PonnuMaapillai registered users can renew their membership by making their renewal fee. Their membership will expire after the stipulated period. You will be guided by message from PonnuMaapillai regarding your membership expiry period.</p>
                  <p align="justify"><u><strong>Legal Disclaimer for Website Content</strong></u></p>
                  <p align="justify">On accessing to the website, you are agreeing to the terms and conditions of the website <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a>. PonnuMaapillai provides the Web site as a paid service to the public. PonnuMaapillai is not responsible for, and expressly disclaims all liability for, damages of any kind arising out of use, reference to, or reliance on any information contained within the site. While the information contained within the site is periodically updated, no guarantee is given that the information provided in this Web site is correct, complete, and up-to-date. Although www.ponnumaapillai.com may include links providing direct access to other Internet resources, including Web sites, PonnuMaapillai is not responsible for the accuracy or content of information contained in these sites. PonnuMaapillai disclaims all warranties, Express or Implied, or Merchantability, fitness for a particular purpose or non-infringement. PonnuMaapillai will not be liable for damages of any kind arising from the use of this <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a> website including but not limited to direct , indirect, incidental , punitive and consequential damages.</p>
                  <p align="justify">Under no circumstances <a href="http://www.ponnumaapillai.com/">www.ponnumaapillai.com</a> shall be held responsible or liable whatsoever or howsoever , arising out due to</p>
                  <p align="justify">Any false information provided by you or on your behalf.</p>
                  <p align="justify">Any unwarranted and unauthorised deed or act by any third party relating to any information given by you or on your behalf.</p>
                  <p align="justify">Any type of cybercrime attempted or committed by anyone on information given by you.</p>
                  <p align="justify">Outcome of during any interaction in a meeting, call, SMS, chat, e-mail or social media posts at any point of time.</p>
                  <p align="justify">Any incident of force-majeure or 'act of god'.</p>
              </div>
          </div>
      </div>
</div>
@endsection